import { Initiative } from "@/types";

export const INITIAL_INITIATIVES: Initiative[] = [
  {
    id: "init-01",
    name: "AlcoEaze Ad Creative Swarm",
    repoName: "tony-brands/alcoeaze-ad-agent",
    brand: "AlcoEaze Supplements",
    description: "Generates high-converting TikTok/Meta UGC video ad hooks, script variations, and countertop packaging retail angles based on top viral competitors.",
    currentState: "PARTIAL",
    classification: "AUTONOMOUS_AGENT",
    strategicVerdict: "KEEP_AND_SCALE",
    recommendedModel: "Claude 3.5 Sonnet (Creative Scripts) + GPT-4o-mini (Vision Analysis)",
    memoryTier: "ISOLATED_BRAND_SILO",
    revenueImpact: "HIGH_REVENUE",
    estimatedLaborHoursSavedPerWeek: 16,
    monthlyRevenueLiftEst: 28500,
    monthlyTokenCostEst: 18.40,
    architectNotes: "Direct revenue driver. Keep brand voice, formulation claims, and FTC compliance in isolated brand memory. Do not let competitor analysis leak into other brands."
  },
  {
    id: "init-02",
    name: "Shopify Auto-Reorder & PO Generator",
    repoName: "tony-brands/shopify-fba-reorder",
    brand: "Health & Fitness / Amazon FBA",
    description: "Custom AI script attempting to predict stockout dates and draft Purchase Orders to Chinese co-packers using LLM prompts.",
    currentState: "AI_MVP_BUGGY",
    classification: "EXISTING_SAAS",
    strategicVerdict: "REPLACE_WITH_SAAS",
    recommendedModel: "Off-The-Shelf SaaS (Stocky / Inventory Planner by Sage)",
    memoryTier: "EPHEMERAL_SCRATCHPAD",
    revenueImpact: "LABOR_SAVING_ONLY",
    estimatedLaborHoursSavedPerWeek: 12,
    monthlyRevenueLiftEst: 0,
    monthlyTokenCostEst: 0,
    architectNotes: "Classic overengineering trap. Mathematical lead times and safety stock should NEVER be calculated by an LLM hallucinating integers. Use dedicated inventory SaaS."
  },
  {
    id: "init-03",
    name: "TikTok Shop Creator Outreach Lead Engine",
    repoName: "tony-brands/tiktok-creator-outreach",
    brand: "TikTok Shop Merch & Apparel",
    description: "Scrapes micro-influencers and evaluates engagement rates for sample seeding campaigns.",
    currentState: "PARTIAL",
    classification: "AUTONOMOUS_AGENT",
    strategicVerdict: "CONSOLIDATE",
    consolidationGroup: "Unified Creator Seeding Engine (Repos #3, #4, #5 combined)",
    recommendedModel: "GPT-4o-mini (Structured Extraction) + Inngest Orchestration",
    memoryTier: "SHARED_ENTERPRISE",
    revenueImpact: "CRITICAL_REVENUE",
    estimatedLaborHoursSavedPerWeek: 22,
    monthlyRevenueLiftEst: 45000,
    monthlyTokenCostEst: 24.50,
    architectNotes: "Combine with #4 (Scraper) and #5 (Pitch Generator) into a single event-driven pipeline. 1 multi-step agent beats 3 disconnected repos."
  },
  {
    id: "init-04",
    name: "TikTok Influencer Raw Scraper",
    repoName: "tony-brands/tiktok-raw-scraper",
    brand: "TikTok Shop Merch & Apparel",
    description: "Python Playwright scraper trying to bypass TikTok anti-bot mechanisms to harvest DM contact info.",
    currentState: "AI_MVP_BUGGY",
    classification: "DETERMINISTIC_SOFTWARE",
    strategicVerdict: "CONSOLIDATE",
    consolidationGroup: "Unified Creator Seeding Engine (Repos #3, #4, #5 combined)",
    recommendedModel: "None / Apify Actor Webhook (Deterministic)",
    memoryTier: "EPHEMERAL_SCRATCHPAD",
    revenueImpact: "MODERATE_REVENUE",
    estimatedLaborHoursSavedPerWeek: 8,
    monthlyRevenueLiftEst: 0,
    monthlyTokenCostEst: 0,
    architectNotes: "Stop maintaining custom scraping infrastructure that breaks weekly. Delegate to Apify or Modash actor, ingest JSON via webhook into Repo #3."
  },
  {
    id: "init-05",
    name: "Creator Personalized Pitch Drafter",
    repoName: "tony-brands/creator-pitch-vault",
    brand: "Cross-Brand Portfolio",
    description: "Directory of Markdown prompts and CSVs used manually to copy-paste outreach messages into TikTok & Instagram DMs.",
    currentState: "PROMPT_LIBRARY",
    classification: "DOCUMENTED_SOP",
    strategicVerdict: "CONSOLIDATE",
    consolidationGroup: "Unified Creator Seeding Engine (Repos #3, #4, #5 combined)",
    recommendedModel: "Gemini 2.0 Flash (Fast Personalization)",
    memoryTier: "SHARED_ENTERPRISE",
    revenueImpact: "HIGH_REVENUE",
    estimatedLaborHoursSavedPerWeek: 14,
    monthlyRevenueLiftEst: 15000,
    monthlyTokenCostEst: 6.20,
    architectNotes: "Prompts should not be a static repo. Ingest winning pitches into Shared Company Intelligence, and call dynamically via Step 3 in unified outreach pipeline."
  },
  {
    id: "init-06",
    name: "Discord Community Moderator AI",
    repoName: "tony-brands/discord-mod-agent",
    brand: "Discord Community (TikTok Shop)",
    description: "Complex LangChain conversational bot designed to answer community questions and moderate spam 24/7.",
    currentState: "CONCEPT_FDD",
    classification: "DOCUMENTED_SOP",
    strategicVerdict: "KILL_STOP_BUILDING",
    recommendedModel: "None / Discord AutoMod + Standard Human SOP",
    memoryTier: "EPHEMERAL_SCRATCHPAD",
    revenueImpact: "ZERO_NET_ROI",
    estimatedLaborHoursSavedPerWeek: 2,
    monthlyRevenueLiftEst: 0,
    monthlyTokenCostEst: 0,
    architectNotes: "Stop building immediately. High hallucination risk, negative user sentiment when bots pretend to be human, and Discord native AutoMod already catches 98% of spam."
  },
  {
    id: "init-07",
    name: "Klaviyo Dynamic Flow Intelligence",
    repoName: "tony-brands/klaviyo-flow-optimizer",
    brand: "Cross-Brand E-Commerce",
    description: "Webhooks triggering tailored email sequence timing and product bundle recommendations based on customer browse behavior.",
    currentState: "PARTIAL",
    classification: "DETERMINISTIC_SOFTWARE",
    strategicVerdict: "KEEP_AND_SCALE",
    recommendedModel: "None / Deterministic Klaviyo Liquid + Webhook Rules",
    memoryTier: "SHARED_ENTERPRISE",
    revenueImpact: "HIGH_REVENUE",
    estimatedLaborHoursSavedPerWeek: 6,
    monthlyRevenueLiftEst: 18500,
    monthlyTokenCostEst: 0,
    architectNotes: "This should NOT be an AI agent. Deterministic logic (event triggers, cart value thresholds, timing rules) is 100% reliable, zero token cost, and directly prints revenue."
  },
  {
    id: "init-08",
    name: "Multi-Brand Central Inventory & Stock Sync",
    repoName: "tony-brands/multi-brand-inventory-sync",
    brand: "Cross-Brand Infrastructure",
    description: "Custom AI-assisted Node service syncing warehouse inventory across Shopify, Amazon FBA, and TikTok Shop.",
    currentState: "AI_MVP_BUGGY",
    classification: "DETERMINISTIC_SOFTWARE",
    strategicVerdict: "BUILD_CORE_INFRA",
    recommendedModel: "Deterministic TypeScript Engine + Inngest Queues",
    memoryTier: "SHARED_ENTERPRISE",
    revenueImpact: "CRITICAL_REVENUE",
    estimatedLaborHoursSavedPerWeek: 15,
    monthlyRevenueLiftEst: 32000,
    monthlyTokenCostEst: 0,
    architectNotes: "Foundational infrastructure. Strip all AI wrappers; rebuild as resilient idempotent TypeScript queues with ACID locks to stop overselling and channel bans."
  },
  {
    id: "init-09",
    name: "Autonomous Voice Support Representative",
    repoName: "tony-brands/vapi-support-agent",
    brand: "Health & Supplements",
    description: "25-page Functional Design Document proposing full conversational inbound phone support for shipping inquiries.",
    currentState: "CONCEPT_FDD",
    classification: "DOCUMENTED_SOP",
    strategicVerdict: "KILL_STOP_BUILDING",
    recommendedModel: "Off-The-Shelf Helpdesk (Gorgias AI / Zendesk)",
    memoryTier: "ISOLATED_BRAND_SILO",
    revenueImpact: "ZERO_NET_ROI",
    estimatedLaborHoursSavedPerWeek: 4,
    monthlyRevenueLiftEst: 0,
    monthlyTokenCostEst: 0,
    architectNotes: "Do not build. Supplements customers calling about late delivery want resolution, not synthetic conversational loops. Gorgias auto-responder handles this natively for $50/mo."
  },
  {
    id: "init-10",
    name: "Shared Company Intelligence Layer",
    repoName: "tony-brands/shared-company-brain",
    brand: "All Brands (Central Backbone)",
    description: "Unified knowledge repository storing brand voice standards, SOPs, top ad scripts, and evaluated agent outputs.",
    currentState: "CONCEPT_FDD",
    classification: "DETERMINISTIC_SOFTWARE",
    strategicVerdict: "BUILD_CORE_INFRA",
    recommendedModel: "Supabase pgvector + Mem0 Tenant Isolation",
    memoryTier: "SHARED_ENTERPRISE",
    revenueImpact: "CRITICAL_REVENUE",
    estimatedLaborHoursSavedPerWeek: 25,
    monthlyRevenueLiftEst: 50000,
    monthlyTokenCostEst: 12.00,
    architectNotes: "The single most important missing link. Prevents having to re-explain company context to 10 different agents. Solves cross-agent intelligence with tenant isolation."
  },
  {
    id: "init-11",
    name: "Amazon Listing Keyword & SEO Optimizer",
    repoName: "tony-brands/amazon-listing-ai",
    brand: "Amazon FBA Health",
    description: "Periodic audit tool that checks competitor ASIN bullet points, backend search terms, and compliance restrictions.",
    currentState: "PROMPT_LIBRARY",
    classification: "DETERMINISTIC_SOFTWARE",
    strategicVerdict: "KEEP_AND_SCALE",
    recommendedModel: "Gemini 2.0 Flash (Fast Semantic Diffing)",
    memoryTier: "ISOLATED_BRAND_SILO",
    revenueImpact: "MODERATE_REVENUE",
    estimatedLaborHoursSavedPerWeek: 7,
    monthlyRevenueLiftEst: 11200,
    monthlyTokenCostEst: 3.50,
    architectNotes: "Turn the prompt library into a weekly cron job via Inngest. Feeds directly into Amazon SP-API draft listings for 1-click founder approval."
  },
  {
    id: "init-12",
    name: "Weekly Executive P&L & Ad Spend Aggregator",
    repoName: "tony-brands/executive-pnl-bot",
    brand: "Portfolio Executive Level",
    description: "Python script attempting to fetch Meta Ads, TikTok Ads, Shopify revenue, and QuickBooks data to generate weekly PDF summaries.",
    currentState: "AI_MVP_BUGGY",
    classification: "EXISTING_SAAS",
    strategicVerdict: "REPLACE_WITH_SAAS",
    recommendedModel: "Existing SaaS (Lifetimely / Triple Whale)",
    memoryTier: "SHARED_ENTERPRISE",
    revenueImpact: "LABOR_SAVING_ONLY",
    estimatedLaborHoursSavedPerWeek: 8,
    monthlyRevenueLiftEst: 0,
    monthlyTokenCostEst: 0,
    architectNotes: "Maintaining API connectors for Meta, TikTok, Shopify, and QuickBooks as custom code is an ongoing maintenance nightmare. Adopt Lifetimely for $49/mo."
  }
];

export const PRESET_AUDIT_PROMPTS = [
  {
    label: "TikTok Creator Outreach Sprawl (3 Repos)",
    brand: "TikTok Shop Merch",
    content: "We have 3 separate repositories: one for scraping creators using Playwright, one for ranking them by engagement, and a prompt library for outreach DMs. Should we maintain these as 3 microservices or combine them? Where should creator response history live?"
  },
  {
    label: "Customer Service Voice Bot vs Helpdesk",
    brand: "AlcoEaze Supplements",
    content: "Founder wants to build a custom conversational AI voice agent using Vapi + OpenAI for incoming phone calls regarding shipping status and product ingredients. We have a 20-page FDD. Should we build this agent or use traditional software?"
  },
  {
    label: "Multi-Brand Shared Memory Architecture",
    brand: "All Brands Ecosystem",
    content: "We run AlcoEaze, an apparel brand, and an Amazon FBA health store. What data should be shared across our AI coding and operational agents, and what strictly needs to be isolated between brands? Where should memory live?"
  },
  {
    label: "Shopify Reordering & Inventory Forecast",
    brand: "Health & Fitness Portfolio",
    content: "Our team wrote a 400-line Python script using GPT-4o to calculate reorder quantities from our Shopify inventory CSV. It keeps giving inconsistent numbers for lead times. How should this be architected?"
  }
];
